/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/**********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : .
 **********************************************************************************************************************/

#include "hal_data.h"
#include "common_util.h"

#include "application_config.h"
#if defined(REQUIRE_OSPI_OPEN)
#include "ospi_b_ep.h"
#endif

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Time given to the parallel graphics panel to complete its own power-on reset
 * before the GLCD pins start driving it. Kept as a macro so it can be swept
 * quickly when the panel comes up blank — try 500 or 1000 before concluding
 * the panel or its cable is at fault. */
#ifndef PANEL_POWER_ON_RESET_DELAY_MS
#define PANEL_POWER_ON_RESET_DELAY_MS  (300)
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* Do nothing. This function will not be called in RTOS enabled project. */
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        /* In order to prevent the parallel graphics panel from power-on-reset fail, */
        /* make a delay of the signal output including initial level assertion as a workaround. */
        /*
         * Raised from the original 100 ms while chasing a white screen that
         * appeared after the board was unplugged and reconnected. The panel
         * must finish its own power-on reset before the GLCD pins below start
         * driving it; if it is still resetting when the signals arrive it comes
         * up blank and stays that way until the next power cycle.
         *
         * NOTE: only a full power cycle exercises this path. Pressing RESET
         * restarts the MCU but leaves the panel powered, so it will not
         * re-run the panel's power-on reset and the delay has no effect.
         */
        R_BSP_SoftwareDelay(PANEL_POWER_ON_RESET_DELAY_MS, BSP_DELAY_UNITS_MILLISECONDS);
        R_IOPORT_PinsCfg(&IOPORT_CFG_CTRL, &g_bsp_pin_cfg_glcd);

#if BSP_CFG_SDRAM_ENABLED
        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif

#if defined(REQUIRE_OSPI_OPEN)
        fsp_err_t err = ospi_b_init();
        if(FSP_SUCCESS != err)
        {
            ERROR_INDICATE_LED_ON;
            __BKPT(0);
        }

#if ENABLE_OSPI_8BIT_MODE
        // Important note: In order to use 8D-8D-8D, the data must be written with byte order swap in 16bit unit.
        //                 This project does not provide a solution. It is recommended to swap the data before programming by debugger
        err = ospi_b_set_protocol_to_opi();
        if(FSP_SUCCESS != err)
        {
            ERROR_INDICATE_LED_ON;
            __BKPT(0);
        }
#endif

#if defined(REQUIRE_OSPI_MEMORY_COPY_TO_SDRAM)
        // Note: Starting with FSPv6.0.0, the copy is done by Reset_Handler code.
#endif
#endif
    }
}
